package com.auto.code.generator.core;

import java.io.File;

import com.auto.code.generator.specification.APIType;
import com.auto.code.generator.specification.ApiSpecification;
import com.auto.code.generator.specification.Utility;
import com.sun.codemodel.JCodeModel;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JPackage;

public class ControllerGenerator {
	private static final String PACKAGE_NAME = ".controller";

	public static void generateController(JCodeModel codeModel, ApiSpecification spec, String basePackage,
			String rootPath, String autoGeneRatedFilePath) throws Exception {

		JPackage jp = codeModel._package(basePackage + PACKAGE_NAME);
		JDefinedClass jc = null;
		if (jp._getClass(spec.getController().getClassName()) != null) {
			jc = jp._getClass(spec.getController().getClassName());
		} else {
			jc = jp._class(spec.getController().getClassName());
			jc.annotate(codeModel.ref(Constant.REST_CONTROLLER_ANNOTATION));
			jc.annotate(codeModel.ref(Constant.REQUEST_MAPPING)).param("value", rootPath);
			jc.javadoc().add("Auto generated controller class");
		}
		if (spec.getApiMethodType().equalsIgnoreCase(APIType.POST.name())) {
			ControllerMethodGenerator.generatePostMethod(codeModel, jc, spec, basePackage, autoGeneRatedFilePath);
		}

		if (spec.getApiMethodType().equalsIgnoreCase(APIType.GET.name()))

		{
			ControllerMethodGenerator.generateGetMethod(codeModel, jc, spec, basePackage, autoGeneRatedFilePath);
		}

		if (spec.getApiMethodType().equalsIgnoreCase(APIType.PUT.name())) {
			ControllerMethodGenerator.generatePutMethod(codeModel, jc, spec, basePackage, autoGeneRatedFilePath);
		}

		if (spec.getApiMethodType().equalsIgnoreCase(APIType.DELETE.name()))

		{
			ControllerMethodGenerator.generateDeleteMethod(codeModel, jc, spec, basePackage, autoGeneRatedFilePath);

		}
		codeModel.build(new File(autoGeneRatedFilePath));
		Utility.compileClasses(spec, jp.getPackage().name(), jc.name(), autoGeneRatedFilePath);
	}

}
