package com.auto.code.generator.core;

import org.apache.commons.collections4.CollectionUtils;

import com.auto.code.generator.specification.ApiSpecification;
import com.sun.codemodel.JCodeModel;

public class RequestGenerator extends BaseDomainGenerator {

	public void generateRequest(JCodeModel codeModel, ApiSpecification specification, String basePackage,
			String autoGeneRatedFilePath) throws Exception {
		if (specification != null && specification.getApiRequest() != null
				&& CollectionUtils.isNotEmpty(specification.getApiRequest().getComplexType())) {
			generateComplexType(codeModel, specification.getApiRequest().getComplexType(), basePackage, specification,
					autoGeneRatedFilePath);

		}
		if (specification != null && specification.getApiRequest() != null
				&& specification.getApiRequest().getClassName() != null && specification.getApiRequest().getGenerate()
				&& CollectionUtils.isNotEmpty(specification.getApiRequest().getFields())) {
			generateCore(codeModel, specification.getApiRequest().getClassName(),
					specification.getApiRequest().getFields(), basePackage, specification, autoGeneRatedFilePath);

		}

	}

}
