package com.auto.code.generator.core;

import org.apache.commons.collections4.CollectionUtils;

import com.auto.code.generator.specification.ApiSpecification;
import com.sun.codemodel.JCodeModel;

public class ResponseGenerator extends BaseDomainGenerator {

	public void generateResponse(JCodeModel codeModel, ApiSpecification specification, String basePackage,
			String autoGeneRatedFilePath) throws Exception {
		if (specification != null && specification.getApiResponse() != null
				&& CollectionUtils.isNotEmpty(specification.getApiResponse().getComplexType())) {
			generateComplexType(codeModel, specification.getApiResponse().getComplexType(), basePackage, specification,
					autoGeneRatedFilePath);
		}
		// Create a new package
		if (specification != null && specification.getApiResponse() != null
				&& specification.getApiResponse().getClassName() != null && specification.getApiResponse().getGenerate()
				&& CollectionUtils.isNotEmpty(specification.getApiResponse().getFields())) {
			generateCore(codeModel, specification.getApiResponse().getClassName(),
					specification.getApiResponse().getFields(), basePackage, specification, autoGeneRatedFilePath);

		}
	}

}
